### ISSUE TITLE
Twitter Digit Login not work

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-android#132]
I just finished compiling the new version 2.1.

I configured the gradle.properties file with all richeisti data.

I'm trying to connect / register via twitter digits mo I have problems:

I get a text message with the activation code, the app automatically takes the code and valid returning to home and telling me to wait.

after a few seconds you will see a Toast saying:
"Blob does not exist"

What could be the problem?

It states that the digist twitter codes work because I use them in the web version of q-municate.

**Comment by tatanka987** [comment]
hello @EminDemiri, please provide us full log from start app to getting this toast

**Comment by EminDemiri** [comment]
hello @tatanka987 this is my log on check login with digits:

```
`10-20 18:46:11.613 5290-5290/com.emindemiri.talkme D/Gsm/SmsMessage: SMS SC timestamp: 1476981967000
10-20 18:46:11.613 5290-5290/com.emindemiri.talkme E/Gsm/SmsMessage: hasUserDataHeader : false
10-20 18:46:11.763 5290-5290/com.emindemiri.talkme W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
10-20 18:46:11.768 5290-5290/com.emindemiri.talkme W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
10-20 18:46:11.833 5290-5290/com.emindemiri.talkme W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
10-20 18:46:21.808 5290-5297/com.emindemiri.talkme I/dalvikvm: Jit: resizing JitTable from 4096 to 8192
10-20 18:46:31.058 5290-5290/com.emindemiri.talkme D/BaseAuthActivity: Success login by number: +393272421650
10-20 18:46:31.188 5290-5290/com.emindemiri.talkme D/BaseActivity: onAttachFragment
10-20 18:46:31.333 5290-5290/com.emindemiri.talkme D/QBService: onCreate()
10-20 18:46:31.338 5290-5290/com.emindemiri.talkme D/QBService: onStartCommand
10-20 18:46:31.338 5290-5290/com.emindemiri.talkme D/QBService: service started with resultAction=social_login_action
10-20 18:46:31.358 5290-7224/com.emindemiri.talkme D/QBASDK: =========================================================
                                                             === REQUEST ==== 9e40ba3e-e179-4bc7-8e72-b23d2d0c5af3 ===
                                                             REQUEST
                                                                 GET https://api.quickblox.com/account_settings.json
                                                             HEADERS
                                                                 QB-Account-Key=xxxxxxxxxxxxxxxxxxxx
                                                             PARAMETERS
                                                             
                                                             INLINE
                                                                 GET https://api.quickblox.com/account_settings.json
10-20 18:46:31.408 5290-5290/com.emindemiri.talkme D/SensorManager: unregisterListener:: Trklfufi 9 budiwrd5mrfo5WirfulblrwuFmfulTrklfufi$KfukwiFmfulTrklfufiRvht@,)-8()/8
10-20 18:46:31.408 5290-5290/com.emindemiri.talkme D/Sensors: Remain listener = Sending .. normal delay 200ms
10-20 18:46:31.408 5290-5290/com.emindemiri.talkme I/Sensors: sendDelay --- 200000000
10-20 18:46:31.418 5290-5290/com.emindemiri.talkme D/SensorManager: JNI - sendDelay
10-20 18:46:31.423 5290-5290/com.emindemiri.talkme I/SensorManager: Set normal delay = true
10-20 18:46:31.448 5290-5290/com.emindemiri.talkme D/BaseActivity: onRestart
10-20 18:46:31.448 5290-5290/com.emindemiri.talkme D/ActivityLifecycleHandler: onActivityStarted LandingActivity
10-20 18:46:31.558 5290-5290/com.emindemiri.talkme W/ResourceType: Failure getting entry for 0x010802c1 (t=7 e=705) in package 0 (error -75)
10-20 18:46:31.583 5290-5290/com.emindemiri.talkme D/BaseActivity: onStart
10-20 18:46:31.583 5290-5290/com.emindemiri.talkme D/BaseActivity: connectToService()
10-20 18:46:31.628 5290-5290/com.emindemiri.talkme D/ActivityLifecycleHandler: onActivityResumed LandingActivity count of activities = 0
10-20 18:46:31.628 5290-5290/com.emindemiri.talkme D/BaseActivity: onResume
10-20 18:46:31.733 5290-5290/com.emindemiri.talkme D/QBService: onBind
10-20 18:46:31.833 5290-5290/com.emindemiri.talkme D/BaseActivity: onServiceConnected
10-20 18:46:32.988 5290-5290/com.emindemiri.talkme I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
10-20 18:46:33.408 5290-5290/com.emindemiri.talkme D/QBASDK: onActivityStopped0
10-20 18:46:34.013 5290-5292/com.emindemiri.talkme D/dalvikvm: GC_CONCURRENT freed 1449K, 14% free 15233K/17543K, paused 100ms+28ms, total 373ms
10-20 18:46:34.393 5290-7224/com.emindemiri.talkme D/QBASDK: *********************************************************
                                                             *** RESPONSE *** 9e40ba3e-e179-4bc7-8e72-b23d2d0c5af3 ***
                                                             STATUS : 200 
                                                             HEADERS
                                                                 QuickBlox-REST-API-Version=0.1.1
                                                                 X-Runtime=0.004789
                                                                 ETag="32d11fd422247335fc5790e1dc824c9a"
                                                                 Content-Length=175
                                                                 X-UA-Compatible=IE=Edge,chrome=1
                                                                 X-Request-Id=66e364e61ef45473e1e598f1bd765be2
                                                                 X-Rack-Cache=miss
                                                                 Connection=Close
                                                                 Server=openresty/1.9.15.1
                                                                 Cache-Control=max-age=0, private, must-revalidate
                                                                 Status=200 OK
                                                                 Strict-Transport-Security=max-age=15768000;
                                                                 Date=Thu, 20 Oct 2016 16:46:34 GMT
                                                                 Access-Control-Allow-Origin=*
                                                                 X-Android-Received-Millis=1476981994365
                                                                 Content-Type=application/json; charset=utf-8
                                                                 X-Android-Sent-Millis=1476981994060
                                                             BODY
                                                                 '{"account_id":28544,"api_endpoint":"https://api.quickblox.com","chat_endpoint":"chat.quickblox.com","turnserver_endpoint":"turnserver.quickblox.com","s3_bucket_name":"qbprod"}'
10-20 18:46:34.563 5290-7224/com.emindemiri.talkme D/QBASDK: Retrieved custom endpoints. ApiEndpoint: https://api.quickblox.com, ChatEndpoint: chat.quickblox.com
10-20 18:46:34.563 5290-7224/com.emindemiri.talkme D/Request build:: application_id=46061&auth_key=dHEGHcBMLp8AVnc&nonce=2032655256&timestamp=1476981994
10-20 18:46:34.573 5290-7224/com.emindemiri.talkme D/QBASDK: =========================================================
                                                             === REQUEST ==== de72e26e-a980-446a-bb98-a7a7505c29d2 ===
                                                             REQUEST
                                                                 POST https://api.quickblox.com/session.json
                                                             HEADERS
                                                                 QuickBlox-REST-API-Version=0.1.1
                                                                 QB-SDK=Android 2.6.1
                                                             PARAMETERS
                                                                 application_id=XXXXX
                                                                 auth_key=xxxxxxxxxxxxxxx
nonce=2032655256
                                                                 timestamp=1476981994
                                                                 signature=48fe74066b61559040fabeb056439f5273ed27a8
                                                             INLINE
                                                                 POST https://api.quickblox.com/session.json?application_id=46061&auth_key=dHEGHcBMLp8AVnc&nonce=2032655256&timestamp=1476981994&signature=48fe74066b61559040fabeb056439f5273ed27a8
10-20 18:46:35.433 5290-7224/com.emindemiri.talkme D/QBASDK: *********************************************************
                                                             *** RESPONSE *** de72e26e-a980-446a-bb98-a7a7505c29d2 ***
                                                             STATUS : 201 
                                                             HEADERS
                                                                 QuickBlox-REST-API-Version=0.1.1
                                                                 X-Runtime=0.026749
                                                                 ETag="f906cf05d421621add0a34ab79078cc4"
                                                                 Content-Length=264
                                                                 X-UA-Compatible=IE=Edge,chrome=1
                                                                 X-Request-Id=5babba57718cf65d37aad71468e59ab7
                                                                 X-Rack-Cache=invalidate, pass
                                                                 Connection=Close
                                                                 Server=openresty/1.9.15.1
                                                                 QB-Token-ExpirationDate=2016-10-20 18:46:35 UTC
                                                                 Cache-Control=max-age=0, private, must-revalidate
                                                                 Status=201 Created
                                                                 Strict-Transport-Security=max-age=15768000;
                                                                 Date=Thu, 20 Oct 2016 16:46:35 GMT
                                                                 Access-Control-Allow-Origin=*
                                                                 X-Android-Received-Millis=1476981995428
                                                                 Content-Type=application/json; charset=utf-8
                                                                 X-Android-Sent-Millis=1476981994963
                                                             BODY
                                                                 '{"session":{"_id":"5808f4eba28f9a7fc5000032","application_id":46061,"created_at":"2016-10-20T16:46:35Z","device_id":0,"nonce":2032655256,"token":"b38bbf0901ace4362fca57357a9b1293ec00b3ed","ts":1476981994,"updated_at":"2016-10-20T16:46:35Z","user_id":0,"id":42054}}'
10-20 18:46:35.508 5290-7224/com.emindemiri.talkme D/QBASDK: =========================================================
                                                             === REQUEST ==== 9e91ed76-6a9c-47b5-a366-93ef987d04c4 ===
                                                             REQUEST
                                                                 POST https://api.quickblox.com/login.json
                                                             HEADERS
                                                                 QuickBlox-REST-API-Version=0.1.1
                                                                 QB-SDK=Android 2.6.1
                                                                 QB-Token=b38bbf0901ace4362fca57357a9b1293ec00b3ed
                                                             PARAMETERS
                                                                 provider=twitter_digits
                                                                 twitter_digits[X-Auth-Service-Provider]=https://api.digits.com/1.1/sdk/account.json
                                                                 twitter_digits[X-Verify-Credentials-Authorization]=OAuth oauth_consumer_key="eVkixxxxxxxxxxxxxxxxxxxxx0", oauth_nonce="286275163823807982964403656604600", oauth_signature="Y6UAyHW22yvsD4IVfIpI44XJrMA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1476981991", oauth_token="3567977542-hzrzSoquUNwmNN2P9nHHwU8W7WcHrR5DsiqC3C9", oauth_version="1.0"
                                                             INLINE
                                                                 POST https://api.quickblox.com/login.json?provider=twitter_digits&twitter_digits[X-Auth-Service-Provider]=https%3A%2F%2Fapi.digits.com%2F1.1%2Fsdk%2Faccount.json&twitter_digits[X-Verify-Credentials-Authorization]=OAuth+oauth_consumer_key%3D%22eVkiajcn5iPC5mSC7Wo5W90G0%22%2C+oauth_nonce%3D%22286275163823807982964403656604600%22%2C+oauth_signature%3D%22Y6UAyHW22yvsD4IVfIpI44XJrMA%253D%22%2C+oauth_signature_method%3D%22HMAC-SHA1%22%2C+oauth_timestamp%3D%221476981991%22%2C+oauth_token%3D%223567977542-hzrzSoquUNwmNN2P9nHHwU8W7WcHrR5DsiqC3C9%22%2C+oauth_version%3D%221.0%22
10-20 18:46:36.513 5290-7224/com.emindemiri.talkme D/QBASDK: *********************************************************
                                                             *** RESPONSE *** 9e91ed76-6a9c-47b5-a366-93ef987d04c4 ***
                                                             STATUS : 422 
                                                             HEADERS
                                                                 QuickBlox-REST-API-Version=0.1.1
                                                                 X-Runtime=0.168211
                                                                 Content-Length=38
                                                                 X-UA-Compatible=IE=Edge,chrome=1
                                                                 X-Request-Id=a2885fa3962fe525ace921c397b7be3d
                                                                 X-Rack-Cache=invalidate, pass
                                                                 Connection=Close
                                                                 Server=openresty/1.9.15.1
                                                                 QB-Token-ExpirationDate=2016-10-20 18:46:35 UTC
                                                                 Cache-Control=no-cache
                                                                 Status=422 Unprocessable Entity
                                                                 Date=Thu, 20 Oct 2016 16:46:36 GMT
                                                                 Access-Control-Allow-Origin=*
                                                                 X-Android-Received-Millis=1476981996515
                                                                 Content-Type=application/json; charset=utf-8
                                                                 X-Android-Sent-Millis=1476981995892
                                                             BODY
                                                                 '{"errors":{"blob":["does not exist"]}}'
10-20 18:46:36.523 5290-7224/com.emindemiri.talkme W/System.err: com.quickblox.core.exception.QBResponseException: blob does not exist
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:89)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.quickblox.core.Query.perform(Query.java:261)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.quickblox.users.QBUsers.signInUsingTwitterDigits(QBUsers.java:218)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.qb.helpers.QBAuthHelper.login(QBAuthHelper.java:68)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.qb.commands.rest.QBSocialLoginCommand.perform(QBSocialLoginCommand.java:46)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.core.command.ServiceCommand.execute(ServiceCommand.java:27)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.service.QBService$1.run(QBService.java:601)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-20 18:46:36.548 5290-7224/com.emindemiri.talkme W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-20 18:46:36.553 5290-7224/com.emindemiri.talkme W/System.err:     at java.lang.Thread.run(Thread.java:856)
10-20 18:46:36.558 5290-7224/com.emindemiri.talkme W/System.err: com.quickblox.core.exception.QBResponseException: blob does not exist
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:89)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.quickblox.core.Query.perform(Query.java:261)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.quickblox.users.QBUsers.signInUsingTwitterDigits(QBUsers.java:218)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.qb.helpers.QBAuthHelper.login(QBAuthHelper.java:68)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.qb.commands.rest.QBSocialLoginCommand.perform(QBSocialLoginCommand.java:46)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.core.command.ServiceCommand.execute(ServiceCommand.java:27)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at com.emindemiri.talkme_core.service.QBService$1.run(QBService.java:601)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-20 18:46:36.563 5290-7224/com.emindemiri.talkme W/System.err:     at java.lang.Thread.run(Thread.java:856)
10-20 18:46:36.568 5290-5290/com.emindemiri.talkme D/STEPS: executing social_login_fail_action
10-20 18:46:36.573 5290-7224/com.emindemiri.talkme D/Utils: error =blob does not exist`
```

**Comment by tatanka987** [comment]
hello @EminDemiri, looks like your user has not exist blob id, please try login other phone number or go to admin panel, search your user by phone number and remove data from field "Blob ID" for this user, then try login this user again

**Comment by EminDemiri** [comment]
Hello @tatanka987 , I thank you I solved, the number was already in the database.
