### ISSUE TITLE
org.jivesoftware.smack.SmackException$NoResponseException

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/q-municate-android#14]
Hi,

I am getting this error quit often.
What is the root cause for this?
QBLoginChatCommand is trying to login until succes or timeout but sometimes I get this error.

Any help is appreciated.

Thanks,

Wouter
```
01-04 14:07:41.782    3316-4800/com.codebrothrs.elseapp D/QBASDK﹕ Login to chat, user JID: 1026410-9723, resource: 358240052342300
01-04 14:07:41.782    3316-4874/com.codebrothrs.elseapp W/System.err﹕ org.jivesoftware.smack.SmackException$NoResponseException
01-04 14:07:41.782    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:346)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at org.jivesoftware.smack.tcp.XMPPTCPConnection.login(XMPPTCPConnection.java:244)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.chat.QBChatService.login(QBChatService.java:243)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.chat.QBChatService.login(QBChatService.java:218)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.qb.helpers.QBChatRestHelper.login(QBChatRestHelper.java:48)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.qb.commands.QBLoginChatCommand.tryLogin(QBLoginChatCommand.java:60)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.qb.commands.QBLoginChatCommand.perform(QBLoginChatCommand.java:45)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.core.command.CompositeServiceCommand.perform(CompositeServiceCommand.java:29)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.core.command.ServiceCommand.execute(ServiceCommand.java:27)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.service.QBService$1.run(QBService.java:564)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
```

**Comment by indikaanu83** [comment]
I'm facing the same issue. This happens with Samsung devices most of the time ( i'm using Samsung  s-duos). Pretty annoying. I tried Stackoverflow as well. No clear solution for this.This comes within the SMACK library. 

woutergoossens  - Were you able to find any solution for this ?

Thanks

**Comment by prashant31191** [comment]
config.setSecurityMode(ConnectionConfiguration.SecurityMode.disabled);

**Comment by tatanka987** [comment]
@prashant31191 please add more details about your issue: logs, current and expected result.

**Comment by Abdulqa** [comment]
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 10000ms (~10s). Waited for response using: AndFilter: (StanzaTypeFilter: Presence, OrFilter: (AndFilter: (FromMatchesFilter (ignoreResourcepart): h1@conference.35.171.18.126, MUCUserStatusCodeFilter: status=110), AndFilter: (FromMatchesFilter (full): h1@conference.35.171.18.126/user00000002, StanzaIdFilter: id=5CqwG-161, PresenceTypeFilter: type=error))).
06-28 20:15:33.482 32615-32615/com.br.granplay W/System.err:     at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:260)
