### ISSUE TITLE
Crashed on Register with phone number

### ISSUE THREAD

**Issue by jaggi772** [QuickBlox/q-municate-android#186]

**Comment by jaggi772** [comment]
Not able to use demo. Try to login by number get Crashed every time.

  Process: com.quickblox.q_municate, PID: 16822
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
                                                                              at com.twitter.sdk.android.core.internal.network.GuestAuthenticator.getExpiredToken(GuestAuthenticator.java:65)
                                                                              at com.twitter.sdk.android.core.internal.network.GuestAuthenticator.reauth(GuestAuthenticator.java:50)
                                                                              at com.twitter.sdk.android.core.internal.network.GuestAuthenticator.authenticate(GuestAuthenticator.java:45)
                                                                              at okhttp3.internal.http.HttpEngine.followUpRequest(HttpEngine.java:893)
                                                                              at okhttp3.RealCall.getResponse(RealCall.java:276)
                                                                              at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                              at com.digits.sdk.android.DigitsUserAgentInterceptor.intercept(DigitsUserAgentInterceptor.java:41)
                                                                              at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                              at com.twitter.sdk.android.core.internal.network.GuestAuthInterceptor.intercept(GuestAuthInterceptor.java:53)
                                                                              at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                              at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                              at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                              at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                              at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by tatanka987** [comment]
hi @jaggi772, please provide us detail steps for reproduce this error and specify your changes, which you made in code (if you did they)

**Comment by jaggi772** [comment]
@tatanka987 i have run this demo try to login with number in crashed.But when i install build from play store it works fine.

**Comment by tatanka987** [comment]
Did you follow [these](https://quickblox.com/developers/Q-municate#Q-municate_Android) instructions? Before running Q-municate from source code you have to configure it with your credentials.

**Comment by robertfernanV** [comment]
@tatanka987  Good day I have the same error, and I follow the steps.
Reviewing the documentation I ask you: how to configure notifications if google is now FCM ?, how to get TwittedDigitsApiKey if following the steps of fabric only adds a Key? Do you have a more up-to-date documentation?
Thanks for the answers.

**Comment by tatanka987** [comment]
@robertfernanV below answers on your questions:
1) New Q-municate version will use FCM pushes, you can see how to configure FCM pushes in test branch [QMUN-SPRINT-2](https://github.com/QuickBlox/q-municate-android/tree/QMUN-SPRINT-2)
2) After registration your app on fabric.io you will get needed credentials for using it in Q-municate, please, see [screen](https://gyazo.com/31100dfaff2d1b1342c66da1b54addec)

**Comment by tatanka987** [comment]
Closed, long time inactivity.
